@echo.
@echo [This script is generated by VSHADOW.EXE for the shadow set {25e6604f-019d-4058-88c0-9a6f2d8148e5}]
@echo.

SET SHADOW_SET_ID={25e6604f-019d-4058-88c0-9a6f2d8148e5}
SET SHADOW_ID_1={1e86a539-7026-4309-96b1-43e5bec346a6}
SET SHADOW_DEVICE_1=\\?\GLOBALROOT\Device\HarddiskVolumeShadowCopy1
